/var/log/fbrk/*.log /opt/fbrk-admin/*cron.log /opt/fbrk-admin/enrich.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 www-data adm
    sharedscripts
}
